# Generated by Django 4.0.3 on 2022-04-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('ZAR', 'ZAR'), ('USD', 'USD'), ('GHS', 'GHS')], default='NGN', help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('ZAR', 'ZAR'), ('USD', 'USD'), ('GHS', 'GHS')], help_text='Currency in which amount is set. Allowed values are NGN, GHS, ZAR or USD', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('ZAR', 'ZAR'), ('USD', 'USD'), ('GHS', 'GHS')], help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='primary_contact_email',
            field=models.EmailField(blank=True, help_text='A contact email for the subaccount', max_length=254, null=True, verbose_name='Primary Contact Email'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='primary_contact_phone',
            field=models.CharField(blank=True, help_text='A phone number to call for this subaccount', max_length=20, null=True, verbose_name='primary_contact_phone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('ZAR', 'ZAR'), ('USD', 'USD'), ('GHS', 'GHS')], default='NGN', help_text='Currency of transaction', max_length=4, verbose_name='Currency'),
        ),
    ]
