# Generated by Django 4.0.3 on 2022-04-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0002_alter_invoice_currency_alter_plan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='primary_contact_name',
            field=models.CharField(blank=True, help_text='A contact name for the subaccount', max_length=255, null=True, verbose_name='Primary Contact name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GHS', 'GHS'), ('ZAR', 'ZAR')], default='NGN', help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GHS', 'GHS'), ('ZAR', 'ZAR')], help_text='Currency in which amount is set. Allowed values are NGN, GHS, ZAR or USD', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GHS', 'GHS'), ('ZAR', 'ZAR')], help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GHS', 'GHS'), ('ZAR', 'ZAR')], default='NGN', help_text='Currency of transaction', max_length=4, verbose_name='Currency'),
        ),
    ]
