# Generated by Django 4.0.3 on 2022-04-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0007_alter_invoice_currency_alter_plan_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('GHS', 'GHS')], default='NGN', help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('GHS', 'GHS')], help_text='Currency in which amount is set. Allowed values are NGN, GHS, ZAR or USD', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('biannually', 'biannually'), ('annually', 'annually')], help_text='Interval in words. Valid intervals are: daily, weekly, monthly,biannually, annually', max_length=50, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Name of the be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR', max_length=50, verbose_name='Plan name'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('GHS', 'GHS')], help_text='Three-letter ISO currency. Allowed values are: NGN, GHS, ZAR or USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('GHS', 'GHS')], default='NGN', help_text='Currency of transaction', max_length=4, verbose_name='Currency'),
        ),
    ]
